In [3]:
import pandas as pd

In [4]:
file = "CountiesData_noGeometry_cleaned.csv"
file_df = pd.read_csv(file)
file_df

,ID,Name,Population,Median Age,TotalAgeOvr65,Percent Age Ovr 65
0,0,"Wilkin County, Minnesota",6398,44.3,1177,0.18
1,1,"Red Lake County, Minnesota",4017,42.2,764,0.19
2,2,"Aitkin County, Minnesota",15841,54.5,4977,0.31
3,3,"Clay County, Minnesota",62040,32.6,7875,0.13
4,4,"Faribault County, Minnesota",13966,46.8,3114,0.22
...,...,...,...,...,...,...
82,82,"Pope County, Minnesota",10932,45.9,2505,0.23
83,83,"Ramsey County, Minnesota",537893,34.8,71903,0.13
84,84,"Stevens County, Minnesota",9759,33.1,1675,0.17
85,85,"Swift County, Minnesota",9448,44.1,2017,0.21
86,86,"Winona County, Minnesota",50992,34.5,7889,0.15

In [5]:
top_ten = file_df.sort_values('Population', ascending = False).head(10)
top_ten

,ID,Name,Population,Median Age,TotalAgeOvr65,Percent Age Ovr 65
16,16,"Hennepin County, Minnesota",1224763,36.3,158332,0.13
83,83,"Ramsey County, Minnesota",537893,34.8,71903,0.13
59,59,"Dakota County, Minnesota",414655,37.7,52234,0.13
57,57,"Anoka County, Minnesota",344861,38.2,43117,0.13
65,65,"Washington County, Minnesota",250979,39.2,33303,0.13
56,56,"St. Louis County, Minnesota",200294,41.0,35541,0.18
58,58,"Stearns County, Minnesota",155300,34.1,21391,0.14
30,30,"Olmsted County, Minnesota",151685,37.1,21498,0.14
32,32,"Scott County, Minnesota",141463,36.0,13567,0.10
38,38,"Wright County, Minnesota",131130,36.2,15019,0.11

In [10]:
top_ten.sum()

ID                                                                  494
Name                  Hennepin County, MinnesotaRamsey County, Minne...
Population                                                      3553023
Median Age                                                        370.6
TotalAgeOvr65                                                    465905
Percent Age Ovr 65                                                 1.32
dtype: object